-- Seeds the Administration side-navigation menu (SUPER ADMIN only) with a
-- Users sub-menu underneath it.
INSERT INTO NXTGEN_NAV_MENU
(MENU_NAME, MENU_CODE, MENU_DISPLAY_NAME, MENU_URL, IS_ENABLED, MENU_TYPE, PARENT_MENU_ID, ACCESS_LEVEL)
VALUES
    ('Administration', 'ADMINISTRATION', 'Administration', NULL, 'Y', 'PARENT', NULL, 'SUPER ADMIN');

INSERT INTO NXTGEN_NAV_MENU
(MENU_NAME, MENU_CODE, MENU_DISPLAY_NAME, MENU_URL, IS_ENABLED, MENU_TYPE, PARENT_MENU_ID, ACCESS_LEVEL)
SELECT
    'Users', 'ADMIN_USERS', 'Users', '/administration/users', 'Y', 'CHILD', ID, 'SUPER ADMIN'
FROM NXTGEN_NAV_MENU
WHERE MENU_CODE = 'ADMINISTRATION';
