-- Seeds the grid + column metadata for the Administration > Users grid.
-- DATA_FIELD values match the camelCase keys returned by /api/griddata so the
-- frontend can bind columns directly to the row data.
INSERT INTO NXTGEN_GRID (GRID_NAME, DATA_API, LOADING_MESSAGE, CRE_BY)
VALUES ('USERS_GRID', '/api/griddata?gridName=USERS_GRID', 'Loading users...', 'SYSTEM');

INSERT INTO NXTGEN_GRID_COLUMN
(GRID_ID, COLUMN_NAME, DATA_FIELD, WIDTH, DISPLAY_ORDER, IS_SORTABLE, IS_FILTERABLE, IS_HIDDEN, CRE_BY)
SELECT ID, 'ID', 'id', 80, 1, 'Y', 'N', 'N', 'SYSTEM' FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID'
UNION ALL
SELECT ID, 'EMPLOYEE NAME', 'emplNm', 220, 2, 'Y', 'Y', 'N', 'SYSTEM' FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID'
UNION ALL
SELECT ID, 'USERNAME', 'username', 180, 3, 'Y', 'Y', 'N', 'SYSTEM' FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID'
UNION ALL
SELECT ID, 'EMAIL ADDRESS', 'emailAddress', 240, 4, 'Y', 'Y', 'N', 'SYSTEM' FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID'
UNION ALL
SELECT ID, 'IS ACTIVE', 'actvFlag', 120, 5, 'Y', 'Y', 'N', 'SYSTEM' FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID'
UNION ALL
SELECT ID, 'IS LOCKED', 'isLocked', 120, 6, 'Y', 'Y', 'N', 'SYSTEM' FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID'
UNION ALL
SELECT ID, 'ACTIONS', 'actions', 140, 7, 'N', 'N', 'N', 'SYSTEM' FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID';
