-- Seed the metadata-driven Create User form (NXTGEN_FORM + NXTGEN_FORM_FIELDS).
INSERT INTO NXTGEN_FORM (FORM_NAME, DATA_API, TEMPLATE_TYPE, CRE_BY)
VALUES ('CREATE_USER_FORM', '/api/createnewuser', 'USER_FORM', 'SYSTEM');

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 1, 'ID', 'ID', 'id', 'READONLY',
       'Auto Generate', 'N', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 2, 'FIRST_NAME', 'First Name', 'firstName', 'TEXT',
       'Enter First Name', 'Y', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 3, 'LAST_NAME', 'Last Name', 'lastName', 'TEXT',
       'Enter Last Name', 'Y', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 4, 'EMPLOYEE_NAME', 'Employee Name', 'emplNm', 'READONLY',
       NULL, 'N', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 5, 'USERNAME', 'Username', 'username', 'READONLY',
       NULL, 'N', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 6, 'PASSWORD', 'Password', 'password', 'PASSWORD',
       'Enter Password', 'N', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 7, 'ROLE', 'Role', 'roleId', 'DROPDOWN',
       'Select Role', 'Y', 'N', NULL, 'NXTGEN_ROLES', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 8, 'EMAIL_ADDRESS', 'Email Address', 'emailAddress', 'READONLY',
       NULL, 'N', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 9, 'SUPER_ADMIN', 'Super Admin', 'isSuperAdmin', 'DROPDOWN',
       'Select Yes or No', 'Y', 'N', NULL, 'YES_NO', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';
