-- Metadata-driven grid configuration tables.
-- NXTGEN_GRID holds one row per grid definition; NXTGEN_GRID_COLUMN holds one row
-- per column of that grid, linked back via GRID_ID.
CREATE TABLE NXTGEN_GRID (
    ID               BIGINT AUTO_INCREMENT PRIMARY KEY,
    GRID_NAME        VARCHAR(255)  NOT NULL,
    DATA_API         VARCHAR(4000),
    LOADING_MESSAGE  VARCHAR(4000),
    CRE_BY           VARCHAR(255),
    CRE_DATE         TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE NXTGEN_GRID_COLUMN (
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    GRID_ID        BIGINT        NOT NULL,
    COLUMN_NAME    VARCHAR(255)  NOT NULL,
    DATA_FIELD     VARCHAR(255)  NOT NULL,
    WIDTH          BIGINT,
    DISPLAY_ORDER  BIGINT,
    IS_SORTABLE    VARCHAR(1),
    IS_FILTERABLE  VARCHAR(1),
    IS_HIDDEN      VARCHAR(1),
    CRE_BY         VARCHAR(255),
    CRE_DATE       TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT FK_NXTGEN_GRID_COLUMN_GRID FOREIGN KEY (GRID_ID)
        REFERENCES NXTGEN_GRID (ID),
    INDEX IDX_NXTGEN_GRID_COLUMN_GRID_ID (GRID_ID)
);

-- Side-navigation menu registry. MENU_TYPE distinguishes PARENT vs CHILD rows;
-- PARENT_MENU_ID links a CHILD row to its owning PARENT row (nullable, self-FK).
CREATE TABLE NXTGEN_NAV_MENU (
    ID                 BIGINT AUTO_INCREMENT PRIMARY KEY,
    MENU_NAME          VARCHAR(255) NOT NULL,
    MENU_CODE          VARCHAR(50)  NOT NULL,
    MENU_DISPLAY_NAME  VARCHAR(255),
    MENU_URL           VARCHAR(255),
    IS_ENABLED         CHAR(1)      DEFAULT 'Y',
    MENU_TYPE          VARCHAR(50)  NOT NULL,
    PARENT_MENU_ID     BIGINT       NULL,
    CONSTRAINT UQ_NXTGEN_NAV_MENU_CODE UNIQUE (MENU_CODE),
    CONSTRAINT FK_NXTGEN_NAV_MENU_PARENT FOREIGN KEY (PARENT_MENU_ID)
        REFERENCES NXTGEN_NAV_MENU (ID),
    INDEX IDX_NXTGEN_NAV_MENU_PARENT_ID (PARENT_MENU_ID)
);
