-- Seed a dedicated Edit User form (NXTGEN_FORM + NXTGEN_FORM_FIELDS) that
-- mirrors CREATE_USER_FORM's fields, except:
--   * User ID is read-only (the WH-sourced record cannot be swapped on edit)
--   * Password is removed entirely (editing a user never changes their password)
INSERT INTO NXTGEN_FORM (FORM_NAME, DATA_API, TEMPLATE_TYPE, CRE_BY)
VALUES ('EDIT_USER_FORM', '/api/updateuser', 'USER_FORM', 'SYSTEM');

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 1, 'USER_ID', 'User ID', 'userId', 'SEARCH',
       NULL, 'Y', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 2, 'FIRST_NAME', 'First Name', 'firstName', 'TEXT',
       'Enter First Name', 'Y', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 3, 'LAST_NAME', 'Last Name', 'lastName', 'TEXT',
       'Enter Last Name', 'Y', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 4, 'EMPLOYEE_NAME', 'Employee Name', 'emplNm', 'READONLY',
       NULL, 'N', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 5, 'USERNAME', 'Username', 'username', 'READONLY',
       NULL, 'N', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 6, 'ROLE', 'Role', 'roleId', 'MULTISELECT',
       'Select Role(s)', 'Y', 'N', NULL, 'NXTGEN_ROLES', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 7, 'EMAIL_ADDRESS', 'Email Address', 'emailAddress', 'READONLY',
       NULL, 'N', 'Y', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM', 8, 'SUPER_ADMIN', 'Super Admin', 'isSuperAdmin', 'DROPDOWN',
       'Select Yes or No', 'Y', 'Y', NULL, 'YES_NO', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';
