-- Seeds the metadata-driven Create Group form (NXTGEN_FORM + NXTGEN_FORM_FIELDS).
INSERT INTO NXTGEN_FORM (FORM_NAME, DATA_API, TEMPLATE_TYPE, CRE_BY)
VALUES ('CREATE_GROUP_FORM', '/api/creategroup', 'GROUP_FORM', 'SYSTEM');

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'GROUP_FORM', 1, 'GROUP_NAME', 'Group Name', 'grpName', 'TEXT',
       'Enter Group Name', 'Y', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_GROUP_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'GROUP_FORM', 2, 'DESCRIPTION', 'Description', 'grpDescription', 'TEXT',
       'Enter Description', 'N', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_GROUP_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'GROUP_FORM', 3, 'ACTIVE', 'Active', 'isActive', 'DROPDOWN',
       'Select Yes or No', 'Y', 'N', 'Y', 'YES_NO', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_GROUP_FORM';
