-- Metadata-driven form configuration tables.
-- NXTGEN_FORM holds one row per form definition; NXTGEN_FORM_FIELDS holds one row
-- per field of that form, linked back via FORM_ID.
CREATE TABLE NXTGEN_FORM (
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    FORM_NAME      VARCHAR(255)  NOT NULL,
    DATA_API       VARCHAR(4000),
    TEMPLATE_TYPE  VARCHAR(255),
    CRE_BY         VARCHAR(255),
    CRE_DATE       TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE TABLE NXTGEN_FORM_FIELDS (
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    FORM_ID        BIGINT        NOT NULL,
    TEMPLATE_TYPE  VARCHAR(255),
    DISPLAY_ORDER  BIGINT,
    CRE_BY         VARCHAR(255),
    CRE_DATE       TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT FK_NXTGEN_FORM_FIELDS_FORM FOREIGN KEY (FORM_ID)
        REFERENCES NXTGEN_FORM (ID),
    INDEX IDX_NXTGEN_FORM_FIELDS_FORM_ID (FORM_ID)
);
