-- Adds the "Owner" search-select field to the Create Group form, placed
-- between Description and Active.
UPDATE NXTGEN_FORM_FIELDS
SET DISPLAY_ORDER = DISPLAY_ORDER + 1
WHERE FIELD_NAME = 'ACTIVE'
  AND FORM_ID = (SELECT ID FROM (SELECT ID FROM NXTGEN_FORM WHERE FORM_NAME = 'CREATE_GROUP_FORM') AS form_lookup);

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'GROUP_FORM', 3, 'OWNER', 'Owner', 'groupOwner', 'SEARCH',
       'Search Owner by name', 'N', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_GROUP_FORM';
