-- Adds the "Group" search-multiselect field to both the Create User and
-- Edit User forms (a user must belong to at least one group).
INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM',
       (SELECT MAX(ff.DISPLAY_ORDER) + 1 FROM NXTGEN_FORM_FIELDS ff WHERE ff.FORM_ID = f.ID),
       'GROUP', 'Group', 'groupIds', 'SEARCHMULTISELECT',
       'Search and select group(s)', 'Y', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM',
       (SELECT MAX(ff.DISPLAY_ORDER) + 1 FROM NXTGEN_FORM_FIELDS ff WHERE ff.FORM_ID = f.ID),
       'GROUP', 'Group', 'groupIds', 'SEARCHMULTISELECT',
       'Search and select group(s)', 'Y', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';
