-- Seeds the CMDB side-navigation menu (SUPER ADMIN only) with CI Classes,
-- CI Relationships, and CI Data sub-menus underneath it.
INSERT INTO NXTGEN_NAV_MENU
(MENU_NAME, MENU_CODE, MENU_DISPLAY_NAME, MENU_URL, IS_ENABLED, MENU_TYPE, PARENT_MENU_ID, ACCESS_LEVEL)
VALUES
    ('CMDB', 'CMDB', 'CMDB', NULL, 'Y', 'PARENT', NULL, 'SUPER ADMIN');

INSERT INTO NXTGEN_NAV_MENU
(MENU_NAME, MENU_CODE, MENU_DISPLAY_NAME, MENU_URL, IS_ENABLED, MENU_TYPE, PARENT_MENU_ID, ACCESS_LEVEL)
SELECT
    'CI Classes', 'CMDB_CI_CLASSES', 'CI Classes', '/cmdb/ciclasses', 'Y', 'CHILD', ID, 'SUPER ADMIN'
FROM NXTGEN_NAV_MENU
WHERE MENU_CODE = 'CMDB';

INSERT INTO NXTGEN_NAV_MENU
(MENU_NAME, MENU_CODE, MENU_DISPLAY_NAME, MENU_URL, IS_ENABLED, MENU_TYPE, PARENT_MENU_ID, ACCESS_LEVEL)
SELECT
    'CI Relationships', 'CMDB_CI_RELATIONSHIPS', 'CI Relationships', '/cmdb/cirelationships', 'Y', 'CHILD', ID, 'SUPER ADMIN'
FROM NXTGEN_NAV_MENU
WHERE MENU_CODE = 'CMDB';

INSERT INTO NXTGEN_NAV_MENU
(MENU_NAME, MENU_CODE, MENU_DISPLAY_NAME, MENU_URL, IS_ENABLED, MENU_TYPE, PARENT_MENU_ID, ACCESS_LEVEL)
SELECT
    'CI Data', 'CMDB_CI_DATA', 'CI Data', '/cmdb/cidata', 'Y', 'CHILD', ID, 'SUPER ADMIN'
FROM NXTGEN_NAV_MENU
WHERE MENU_CODE = 'CMDB';
