-- Seeds all Service Catalog sub-categories (one insert per active category).
-- Split out into its own migration file so the sub-category list can be
-- maintained/extended independently from the category seed data.

CREATE TABLE NXTGEN_SVC_SUBCATEGORY (
                                        ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
                                        CATEGORY_ID    BIGINT       NOT NULL,
                                        NAME           VARCHAR(150) NOT NULL,
                                        ICON           VARCHAR(10),
                                        DESCRIPTION    VARCHAR(255),
                                        DISPLAY_ORDER  INT          DEFAULT 0,
                                        IS_ACTIVE      CHAR(1)      DEFAULT 'Y',
                                        CONSTRAINT FK_NXTGEN_SVC_SUBCATEGORY_CATEGORY FOREIGN KEY (CATEGORY_ID) REFERENCES NXTGEN_SVC_CATEGORY (ID),
                                        INDEX IDX_NXTGEN_SVC_SUBCATEGORY_CATEGORY (CATEGORY_ID)
);

-- Seeds all Service Catalog sub-categories (one insert per active category).
-- Split out into its own migration file so the sub-category list can be
-- maintained/extended independently from the category seed data.
SET @cat_hardware = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Hardware');
SET @cat_software = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Software');
SET @cat_access = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Access & Identity');
SET @cat_email = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Email & Collaboration');
SET @cat_network = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Network');
SET @cat_employee = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Employee Services');
SET @cat_cloud = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Cloud Services');
SET @cat_db = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Database Services');
SET @cat_mobile = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Mobile Services');
SET @cat_security = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Security');
SET @cat_printing = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Printing');
-- V42 (already applied earlier in the migration order) renames this category
-- from 'Other IT Services' to 'Other IT Request', so look it up by its
-- current name here.
SET @cat_other = (SELECT ID FROM NXTGEN_SVC_CATEGORY WHERE NAME = 'Other IT Request');

INSERT INTO NXTGEN_SVC_SUBCATEGORY (CATEGORY_ID, NAME, ICON, DESCRIPTION, DISPLAY_ORDER, IS_ACTIVE) VALUES
                                                                                                        (@cat_hardware, 'Laptop', '💻', 'Laptop-related requests', 1, 'Y'),
                                                                                                        (@cat_hardware, 'Desktop', '🖥️', 'Desktop-related requests', 2, 'Y'),
                                                                                                        (@cat_hardware, 'Monitor', '🖥️', 'Monitor requests', 3, 'Y'),
                                                                                                        (@cat_hardware, 'Keyboard & Mouse', '💻', 'Peripheral requests', 4, 'Y'),
                                                                                                        (@cat_hardware, 'Headset', '💻', 'Headset/audio equipment', 5, 'Y'),
                                                                                                        (@cat_hardware, 'Mobile Device', '💻', 'Corporate mobile device', 6, 'Y'),
                                                                                                        (@cat_hardware, 'Printer', '💻', 'Printer-related requests', 7, 'Y'),
                                                                                                        (@cat_hardware, 'Hardware Replacement', '💻', 'Replacement of existing hardware', 8, 'Y'),
                                                                                                        (@cat_hardware, 'Hardware Upgrade', '💻', 'RAM, SSD, etc.', 9, 'Y'),
                                                                                                        (@cat_hardware, 'Other Hardware Request', '💻', 'Other hardware requests', 10, 'Y'),

                                                                                                        (@cat_software, 'Software Installation', '🖥️', 'Install licensed/approved software', 1, 'Y'),
                                                                                                        (@cat_software, 'Software Uninstallation', '🖥️', 'Remove installed software', 2, 'Y'),
                                                                                                        (@cat_software, 'Software Access & Licensing', '🖥️', 'Software access and licensing requests', 3, 'Y'),
                                                                                                        (@cat_software, 'Software Upgrade', '🖥️', 'Upgrade existing software version', 4, 'Y'),
                                                                                                        (@cat_software, 'Software Downgrade', '🖥️', 'Downgrade existing software version', 5, 'Y'),
                                                                                                        (@cat_software, 'Software Configuration', '🖥️', 'Configure installed software', 6, 'Y'),
                                                                                                        (@cat_software, 'Software Troubleshooting', '🖥️', 'Troubleshoot software issues', 7, 'Y'),
                                                                                                        (@cat_software, 'Application Access', '🖥️', 'Access to an application', 8, 'Y'),
                                                                                                        (@cat_software, 'License Renewal', '🖥️', 'Renew an existing software license', 9, 'Y'),
                                                                                                        (@cat_software, 'New Software Request', '🖥️', 'Request a new piece of software', 10, 'Y'),
                                                                                                        (@cat_software, 'Software Compatibility', '🖥️', 'Software compatibility check', 11, 'Y'),
                                                                                                        (@cat_software, 'Antivirus & Security Software', '🖥️', 'Antivirus/security software requests', 12, 'Y'),
                                                                                                        (@cat_software, 'Developer Tools', '🖥️', 'IDEs and developer tooling requests', 13, 'Y'),
                                                                                                        (@cat_software, 'Productivity Software', '🖥️', 'Office/productivity software requests', 14, 'Y'),
                                                                                                        (@cat_software, 'Database Tools', '🖥️', 'Database client/tooling requests', 15, 'Y'),
                                                                                                        (@cat_software, 'Browser & Plugin Support', '🖥️', 'Browser and plugin support', 16, 'Y'),
                                                                                                        (@cat_software, 'Software Exception Request', '🖥️', 'Software policy exception request', 17, 'Y'),
                                                                                                        (@cat_software, 'Other Software Services', '🖥️', 'Other software related requests', 18, 'Y'),

                                                                                                        (@cat_access, 'Application Access', '🔐', 'Access to application', 1, 'Y'),
                                                                                                        (@cat_access, 'VPN Access', '🔐', 'Request VPN access', 2, 'Y'),
                                                                                                        (@cat_access, 'Network Access', '🔐', 'Network access requests', 3, 'Y'),
                                                                                                        (@cat_access, 'Database Access', '🔐', 'DB access', 4, 'Y'),
                                                                                                        (@cat_access, 'Shared Folder Access', '🔐', 'Network/shared folder access', 5, 'Y'),
                                                                                                        (@cat_access, 'Email & Distribution List Access', '🔐', 'Distribution list access', 6, 'Y'),
                                                                                                        (@cat_access, 'Single Sign-On (SSO)', '🔐', 'SSO access', 7, 'Y'),
                                                                                                        (@cat_access, 'Multi-Factor Authentication (MFA)', '🔐', 'MFA enrollment/reset', 8, 'Y'),
                                                                                                        (@cat_access, 'Password & Account Reset', '🔐', 'Password or account reset requests', 9, 'Y'),
                                                                                                        (@cat_access, 'User Account Management', '🔐', 'User account management requests', 10, 'Y'),
                                                                                                        (@cat_access, 'Privileged Access', '🔐', 'Elevated privileges', 11, 'Y'),
                                                                                                        (@cat_access, 'Service Account', '🔐', 'Service account request', 12, 'Y'),
                                                                                                        (@cat_access, 'Remote Desktop Access', '🔐', 'Remote desktop access request', 13, 'Y'),
                                                                                                        (@cat_access, 'Cloud Access', '🔐', 'Cloud platform access request', 14, 'Y'),
                                                                                                        (@cat_access, 'Access Modification', '🔐', 'Modify existing access', 15, 'Y'),
                                                                                                        (@cat_access, 'Access Removal', '🔐', 'Remove existing access', 16, 'Y'),
                                                                                                        (@cat_access, 'Temporary Access', '🔐', 'Temporary access request', 17, 'Y'),
                                                                                                        (@cat_access, 'Other Access & Identity Services', '🔐', 'Other access and identity requests', 18, 'Y'),

                                                                                                        (@cat_email, 'Email Account', '📧', 'Email account requests', 1, 'Y'),
                                                                                                        (@cat_email, 'Mailbox Management', '📧', 'Mailbox management requests', 2, 'Y'),
                                                                                                        (@cat_email, 'Email Access', '📧', 'Email access requests', 3, 'Y'),
                                                                                                        (@cat_email, 'Email Configuration', '📧', 'Email client configuration', 4, 'Y'),
                                                                                                        (@cat_email, 'Email Delivery Issues', '📧', 'Email delivery issue reports', 5, 'Y'),
                                                                                                        (@cat_email, 'Shared Mailbox', '📧', 'Shared mailbox requests', 6, 'Y'),
                                                                                                        (@cat_email, 'Distribution List', '📧', 'Distribution list requests', 7, 'Y'),
                                                                                                        (@cat_email, 'Email Alias', '📧', 'Email alias requests', 8, 'Y'),
                                                                                                        (@cat_email, 'Email Forwarding', '📧', 'Email forwarding setup', 9, 'Y'),
                                                                                                        (@cat_email, 'Microsoft Teams', '📧', 'Microsoft Teams requests', 10, 'Y'),
                                                                                                        (@cat_email, 'Teams Access & Membership', '📧', 'Teams access and membership requests', 11, 'Y'),
                                                                                                        (@cat_email, 'Teams Meeting & Calling', '📧', 'Teams meeting/calling support', 12, 'Y'),
                                                                                                        (@cat_email, 'SharePoint Access', '📧', 'SharePoint access request', 13, 'Y'),
                                                                                                        (@cat_email, 'OneDrive Access', '📧', 'OneDrive access request', 14, 'Y'),
                                                                                                        (@cat_email, 'Collaboration Site', '📧', 'Collaboration site request', 15, 'Y'),
                                                                                                        (@cat_email, 'Calendar & Meeting Support', '📧', 'Calendar/meeting support', 16, 'Y'),
                                                                                                        (@cat_email, 'Email Security & Spam', '📧', 'Email security/spam handling', 17, 'Y'),
                                                                                                        (@cat_email, 'Other Collaboration Services', '📧', 'Other collaboration requests', 18, 'Y'),

                                                                                                        (@cat_network, 'Wi-Fi Access', '🌐', 'Wi-Fi related requests', 1, 'Y'),
                                                                                                        (@cat_network, 'LAN / Wired Network', '🌐', 'LAN/wired network requests', 2, 'Y'),
                                                                                                        (@cat_network, 'VPN Access', '🌐', 'VPN related requests', 3, 'Y'),
                                                                                                        (@cat_network, 'Internet Access', '🌐', 'Internet access requests', 4, 'Y'),
                                                                                                        (@cat_network, 'Remote Network Access', '🌐', 'Remote network access requests', 5, 'Y'),
                                                                                                        (@cat_network, 'Network Connectivity', '🌐', 'Network connectivity issues', 6, 'Y'),
                                                                                                        (@cat_network, 'Network Configuration', '🌐', 'Network configuration requests', 7, 'Y'),
                                                                                                        (@cat_network, 'Firewall Access', '🌐', 'Firewall access requests', 8, 'Y'),
                                                                                                        (@cat_network, 'Network Port Access', '🌐', 'Network port access requests', 9, 'Y'),
                                                                                                        (@cat_network, 'DNS & DHCP', '🌐', 'DNS/DHCP requests', 10, 'Y'),
                                                                                                        (@cat_network, 'IP Address Management', '🌐', 'IP address management requests', 11, 'Y'),
                                                                                                        (@cat_network, 'Proxy Access', '🌐', 'Proxy access requests', 12, 'Y'),
                                                                                                        (@cat_network, 'Network Performance', '🌐', 'Network performance issues', 13, 'Y'),
                                                                                                        (@cat_network, 'Network Outage', '🌐', 'Network outage reports', 14, 'Y'),
                                                                                                        (@cat_network, 'Site-to-Site Connectivity', '🌐', 'Site-to-site connectivity requests', 15, 'Y'),
                                                                                                        (@cat_network, 'Network Security', '🌐', 'Network security requests', 16, 'Y'),
                                                                                                        (@cat_network, 'Network Device Support', '🌐', 'Network device support requests', 17, 'Y'),
                                                                                                        (@cat_network, 'Other Network Services', '🌐', 'Other network related requests', 18, 'Y'),

                                                                                                        (@cat_employee, 'New Joiner', '👤', 'New joiner onboarding IT setup', 1, 'Y'),
                                                                                                        (@cat_employee, 'Transfer', '👤', 'Employee transfer IT updates', 2, 'Y'),

                                                                                                        (@cat_cloud, 'Cloud Account & Access', '☁️', 'Cloud account and access requests', 1, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Resource Provisioning', '☁️', 'Cloud resource provisioning requests', 2, 'Y'),
                                                                                                        (@cat_cloud, 'Virtual Machines', '☁️', 'Virtual machine requests', 3, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Storage', '☁️', 'Cloud storage requests', 4, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Database', '☁️', 'Cloud database requests', 5, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Network', '☁️', 'Cloud network requests', 6, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Application Services', '☁️', 'Cloud application service requests', 7, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Backup & Recovery', '☁️', 'Cloud backup/recovery requests', 8, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Monitoring', '☁️', 'Cloud monitoring requests', 9, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Security', '☁️', 'Cloud security requests', 10, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Firewall & Access', '☁️', 'Cloud firewall/access requests', 11, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Configuration', '☁️', 'Cloud configuration requests', 12, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Migration', '☁️', 'Cloud migration requests', 13, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Deployment', '☁️', 'Cloud deployment requests', 14, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Performance', '☁️', 'Cloud performance issues', 15, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Cost & Billing', '☁️', 'Cloud cost/billing requests', 16, 'Y'),
                                                                                                        (@cat_cloud, 'Cloud Resource Decommissioning', '☁️', 'Cloud resource decommissioning requests', 17, 'Y'),
                                                                                                        (@cat_cloud, 'Other Cloud Services', '☁️', 'Other cloud related requests', 18, 'Y'),

                                                                                                        (@cat_db, 'Database Access', '🗄️', 'Database access request', 1, 'Y'),
                                                                                                        (@cat_db, 'Database Account', '🗄️', 'Database account request', 2, 'Y'),
                                                                                                        (@cat_db, 'Database Creation', '🗄️', 'Database creation request', 3, 'Y'),
                                                                                                        (@cat_db, 'Database Modification', '🗄️', 'Database modification request', 4, 'Y'),
                                                                                                        (@cat_db, 'Database Decommissioning', '🗄️', 'Database decommissioning request', 5, 'Y'),
                                                                                                        (@cat_db, 'Database Backup & Recovery', '🗄️', 'Database backup/recovery request', 6, 'Y'),
                                                                                                        (@cat_db, 'Database Restore', '🗄️', 'Database restore request', 7, 'Y'),
                                                                                                        (@cat_db, 'Database Performance', '🗄️', 'Database performance issue', 8, 'Y'),
                                                                                                        (@cat_db, 'Database Monitoring', '🗄️', 'Database monitoring request', 9, 'Y'),
                                                                                                        (@cat_db, 'Database Configuration', '🗄️', 'Database configuration request', 10, 'Y'),
                                                                                                        (@cat_db, 'Database Migration', '🗄️', 'Database migration request', 11, 'Y'),
                                                                                                        (@cat_db, 'Database Refresh', '🗄️', 'Database refresh request', 12, 'Y'),
                                                                                                        (@cat_db, 'Database Replication', '🗄️', 'Database replication request', 13, 'Y'),
                                                                                                        (@cat_db, 'Database Storage', '🗄️', 'Database storage request', 14, 'Y'),
                                                                                                        (@cat_db, 'Database Security', '🗄️', 'Database security request', 15, 'Y'),
                                                                                                        (@cat_db, 'Database Schema Change', '🗄️', 'Database schema change request', 16, 'Y'),
                                                                                                        (@cat_db, 'SQL Query Support', '🗄️', 'SQL query support request', 17, 'Y'),
                                                                                                        (@cat_db, 'Database Incident Support', '🗄️', 'Database incident support request', 18, 'Y'),
                                                                                                        (@cat_db, 'Database Maintenance', '🗄️', 'Database maintenance request', 19, 'Y'),
                                                                                                        (@cat_db, 'Other Database Services', '🗄️', 'Other database related requests', 20, 'Y'),

                                                                                                        (@cat_mobile, 'Mobile', '📱', 'Mobile device request', 1, 'Y'),
                                                                                                        (@cat_mobile, 'SIM', '📱', 'SIM card request', 2, 'Y'),
                                                                                                        (@cat_mobile, 'MDM', '📱', 'Mobile device management enrollment', 3, 'Y'),

                                                                                                        (@cat_security, 'Security Access', '🛡️', 'Security access request', 1, 'Y'),
                                                                                                        (@cat_security, 'MFA & Authentication', '🛡️', 'MFA/authentication request', 2, 'Y'),
                                                                                                        (@cat_security, 'Password & Credential Security', '🛡️', 'Password/credential security request', 3, 'Y'),
                                                                                                        (@cat_security, 'Privileged Access', '🛡️', 'Privileged access request', 4, 'Y'),
                                                                                                        (@cat_security, 'Security Software', '🛡️', 'Security software request', 5, 'Y'),
                                                                                                        (@cat_security, 'Antivirus & Endpoint Security', '🛡️', 'Antivirus/endpoint security request', 6, 'Y'),
                                                                                                        (@cat_security, 'Firewall & Network Security', '🛡️', 'Firewall/network security request', 7, 'Y'),
                                                                                                        (@cat_security, 'Security Exception', '🛡️', 'Security exception request', 8, 'Y'),
                                                                                                        (@cat_security, 'Security Incident', '🛡️', 'Security incident report', 9, 'Y'),
                                                                                                        (@cat_security, 'Phishing & Suspicious Email', '🛡️', 'Phishing/suspicious email report', 10, 'Y'),
                                                                                                        (@cat_security, 'Malware & Virus Support', '🛡️', 'Malware/virus support request', 11, 'Y'),
                                                                                                        (@cat_security, 'Data Security', '🛡️', 'Data security request', 12, 'Y'),
                                                                                                        (@cat_security, 'Encryption Services', '🛡️', 'Encryption service request', 13, 'Y'),
                                                                                                        (@cat_security, 'Vulnerability Management', '🛡️', 'Vulnerability management request', 14, 'Y'),
                                                                                                        (@cat_security, 'Security Assessment', '🛡️', 'Security assessment request', 15, 'Y'),
                                                                                                        (@cat_security, 'Security Compliance', '🛡️', 'Security compliance request', 16, 'Y'),
                                                                                                        (@cat_security, 'Security Monitoring', '🛡️', 'Security monitoring request', 17, 'Y'),
                                                                                                        (@cat_security, 'Identity & Access Security', '🛡️', 'Identity/access security request', 18, 'Y'),
                                                                                                        (@cat_security, 'Device Security', '🛡️', 'Device security request', 19, 'Y'),
                                                                                                        (@cat_security, 'Other Security Services', '🛡️', 'Other security related requests', 20, 'Y'),

                                                                                                        (@cat_printing, 'Printer Access', '🖨️', 'Printer access request', 1, 'Y'),
                                                                                                        (@cat_printing, 'Printer Issue', '🖨️', 'Printer issue report', 2, 'Y'),

                                                                                                        (@cat_other, 'General IT Request', '🔧', 'General/other IT request', 1, 'Y'),
                                                                                                        (@cat_other, 'IT Consultation', '🔧', 'IT consultation request', 2, 'Y'),
                                                                                                        (@cat_other, 'IT Information Request', '🔧', 'IT information request', 3, 'Y'),
                                                                                                        (@cat_other, 'IT Account Support', '🔧', 'IT account support request', 4, 'Y'),
                                                                                                        (@cat_other, 'IT Asset Inquiry', '🔧', 'IT asset inquiry request', 5, 'Y'),
                                                                                                        (@cat_other, 'IT Configuration Request', '🔧', 'IT configuration request', 6, 'Y'),
                                                                                                        (@cat_other, 'IT Integration Request', '🔧', 'IT integration request', 7, 'Y'),
                                                                                                        (@cat_other, 'Data & Reporting Request', '🔧', 'Data/reporting request', 8, 'Y'),
                                                                                                        (@cat_other, 'Automation Request', '🔧', 'Automation request', 9, 'Y'),
                                                                                                        (@cat_other, 'IT Documentation Request', '🔧', 'IT documentation request', 10, 'Y'),
                                                                                                        (@cat_other, 'Environment Request', '🔧', 'Environment request', 11, 'Y'),
                                                                                                        (@cat_other, 'IT Monitoring Request', '🔧', 'IT monitoring request', 12, 'Y'),
                                                                                                        (@cat_other, 'IT Maintenance Request', '🔧', 'IT maintenance request', 13, 'Y'),
                                                                                                        (@cat_other, 'IT Onboarding Support', '🔧', 'IT onboarding support request', 14, 'Y'),
                                                                                                        (@cat_other, 'IT Offboarding Support', '🔧', 'IT offboarding support request', 15, 'Y'),
                                                                                                        (@cat_other, 'IT Training & Support', '🔧', 'IT training/support request', 16, 'Y'),
                                                                                                        (@cat_other, 'Technology Evaluation', '🔧', 'Technology evaluation request', 17, 'Y'),
                                                                                                        (@cat_other, 'New IT Service Request', '🔧', 'New IT service request', 18, 'Y'),
                                                                                                        (@cat_other, 'Custom IT Request', '🔧', 'Custom IT request', 19, 'Y'),
                                                                                                        (@cat_other, 'Other', '🔧', 'Other IT request', 20, 'Y');
