-- 1) Users grid: hide the ID column (kept in the row data because row actions
--    and row keys still rely on it).
UPDATE NXTGEN_GRID_COLUMN
SET IS_HIDDEN = 'Y'
WHERE DATA_FIELD = 'id'
  AND GRID_ID = (SELECT ID FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID');

-- 2) Create User / Edit User forms: "Password needs reset" and "Active" dropdowns.
INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM',
       (SELECT MAX(ff.DISPLAY_ORDER) + 1 FROM NXTGEN_FORM_FIELDS ff WHERE ff.FORM_ID = f.ID),
       'PASSWORD_RESET_REQUIRED', 'Password needs reset', 'passwordResetRequired', 'DROPDOWN',
       'Select Yes or No', 'Y', 'N', 'Y', 'YES_NO', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM',
       (SELECT MAX(ff.DISPLAY_ORDER) + 1 FROM NXTGEN_FORM_FIELDS ff WHERE ff.FORM_ID = f.ID),
       'ACTIVE', 'Active', 'isActive', 'DROPDOWN',
       'Select Yes or No', 'Y', 'N', 'Y', 'YES_NO', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CREATE_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM',
       (SELECT MAX(ff.DISPLAY_ORDER) + 1 FROM NXTGEN_FORM_FIELDS ff WHERE ff.FORM_ID = f.ID),
       'PASSWORD_RESET_REQUIRED', 'Password needs reset', 'passwordResetRequired', 'DROPDOWN',
       'Select Yes or No', 'Y', 'N', NULL, 'YES_NO', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'USER_FORM',
       (SELECT MAX(ff.DISPLAY_ORDER) + 1 FROM NXTGEN_FORM_FIELDS ff WHERE ff.FORM_ID = f.ID),
       'ACTIVE', 'Active', 'isActive', 'DROPDOWN',
       'Select Yes or No', 'Y', 'N', NULL, 'YES_NO', 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'EDIT_USER_FORM';

-- 3) Forced password-reset popup (title/message) and its form + fields.
INSERT INTO NXTGEN_POPUP_CONFIG (POPUP_NAME, TITLE, DISPLAY_MSG, IS_ENABLED, CRE_BY)
VALUES ('FORCE_PASSWORD_RESET', 'Reset Your Password',
        'For security reasons you must set a new password before you can continue.', 'Y', 'SYSTEM');

INSERT INTO NXTGEN_FORM (FORM_NAME, DATA_API, TEMPLATE_TYPE, SUBMIT_LABEL, CRE_BY)
VALUES ('CHANGE_PASSWORD_FORM', '/api/changepassword', 'PASSWORD_FORM', 'Change Password', 'SYSTEM');

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'PASSWORD_FORM', 1, 'NEW_PASSWORD', 'New Password', 'newPassword', 'PASSWORD',
       'Enter new password', 'Y', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CHANGE_PASSWORD_FORM';

INSERT INTO NXTGEN_FORM_FIELDS
(FORM_ID, TEMPLATE_TYPE, DISPLAY_ORDER, FIELD_NAME, FIELD_LABEL, DATA_FIELD, FIELD_TYPE,
 PLACEHOLDER, IS_MANDATORY, IS_READONLY, DEFAULT_VALUE, OPTIONS_SOURCE, CRE_BY)
SELECT f.ID, 'PASSWORD_FORM', 2, 'REPEAT_NEW_PASSWORD', 'Repeat New Password', 'confirmPassword', 'PASSWORD',
       'Repeat new password', 'Y', 'N', NULL, NULL, 'SYSTEM'
FROM NXTGEN_FORM f WHERE f.FORM_NAME = 'CHANGE_PASSWORD_FORM';
