-- Adds the "LAST LOGIN DATE" column to the Users grid, right after IS LOCKED
-- (ACTIONS is pushed to the end).
UPDATE NXTGEN_GRID_COLUMN
SET DISPLAY_ORDER = DISPLAY_ORDER + 1
WHERE DATA_FIELD = 'actions'
  AND GRID_ID = (SELECT ID FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID');

INSERT INTO NXTGEN_GRID_COLUMN
(GRID_ID, COLUMN_NAME, DATA_FIELD, WIDTH, DISPLAY_ORDER, IS_SORTABLE, IS_FILTERABLE, IS_HIDDEN, CRE_BY)
SELECT ID, 'LAST LOGIN DATE', 'lastLoginDate', 180, 7, 'Y', 'Y', 'N', 'SYSTEM'
FROM NXTGEN_GRID WHERE GRID_NAME = 'USERS_GRID';
