-- User authentication tables.
-- NXTGEN_USERS_MASTER holds one row per application user (credentials + status flags).
-- NXTGEN_USERS_AUDIT records user activity (e.g. login success/failure) for traceability.
CREATE TABLE NXTGEN_USERS_MASTER (
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY,
    FIRST_NM       VARCHAR(90)   NOT NULL,
    LAST_NM        VARCHAR(90)   NOT NULL,
    EMPL_NM        VARCHAR(150)  NOT NULL,
    USERNAME       VARCHAR(255)  NOT NULL,
    PASSWORD       VARCHAR(255)  NOT NULL,
    EMAIL_ADDRESS  VARCHAR(255)  NOT NULL,
    ACTV_FLAG      VARCHAR(1)    DEFAULT 'Y',
    IS_LOCKED      CHAR(1)       DEFAULT 'N',
    IS_SUP_ADMIN   CHAR(1)       DEFAULT 'N',
    CONSTRAINT UQ_NXTGEN_USERS_MASTER_USERNAME UNIQUE (USERNAME)
);

CREATE TABLE NXTGEN_USERS_AUDIT (
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME  VARCHAR(255)  NOT NULL,
    ACTIVITY  VARCHAR(255)  NOT NULL,
    CRE_BY    VARCHAR(255),
    CRE_DATE  TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
    INDEX IDX_NXTGEN_USERS_AUDIT_USERNAME (USERNAME)
);
