-- Role management tables.
-- NXTGEN_ROLES holds one row per defined role; NXTGEN_USER_ROLES is the
-- user-to-role assignment table (many-to-many: one user can have multiple roles).
CREATE TABLE NXTGEN_ROLES (
    ID           BIGINT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME    VARCHAR(255)  NOT NULL,
    DESCRIPTION  VARCHAR(255),
    IS_ACTIVE    CHAR(1)       DEFAULT 'Y',
    CONSTRAINT UQ_NXTGEN_ROLES_ROLE_NAME UNIQUE (ROLE_NAME)
);

CREATE TABLE NXTGEN_USER_ROLES (
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID   BIGINT        NOT NULL,
    USERNAME  VARCHAR(255)  NOT NULL,
    ROLE_ID   BIGINT        NOT NULL,
    CRE_BY    VARCHAR(255),
    CRE_DATE  TIMESTAMP(6)  DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT FK_NXTGEN_USER_ROLES_USER FOREIGN KEY (USER_ID)
        REFERENCES NXTGEN_USERS_MASTER (ID),
    CONSTRAINT FK_NXTGEN_USER_ROLES_ROLE FOREIGN KEY (ROLE_ID)
        REFERENCES NXTGEN_ROLES (ID),
    CONSTRAINT UQ_NXTGEN_USER_ROLES_USER_ROLE UNIQUE (USER_ID, ROLE_ID),
    INDEX IDX_NXTGEN_USER_ROLES_USER_ID (USER_ID),
    INDEX IDX_NXTGEN_USER_ROLES_ROLE_ID (ROLE_ID)
);
